[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[services]]
name = "finance-app-backend"

[services.variables]
NODE_ENV = "production"
PORT = "${{PORT}}"
