[build]
  builder = "dockerfile"

[deploy]
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environments.production.variables]
  NODE_ENV = "production"
  JWT_EXPIRES_IN = "15m"
  JWT_REFRESH_EXPIRES_IN = "7d"
  COINGECKO_API_URL = "https://api.coingecko.com/api/v3"
