[build]
  builder = "nixpacks"
  buildCommand = "npm install && cd server && npm install"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environments.production.variables]
  NODE_ENV = "production"
  JWT_EXPIRES_IN = "15m"
  JWT_REFRESH_EXPIRES_IN = "7d"
  COINGECKO_API_URL = "https://api.coingecko.com/api/v3"
